server:
  port: 8080

spring:
  application:
    name: rocketmq-test

rocketmq:
  name-server: 192.168.233.128:9876;192.168.233.128:9877;192.168.233.128:9878
  producer:
    # 生产者组
    group: producer-group1
    # 发送消息超时时间，默认3000
    send-message-timeout: 30000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
